Akilan1999/p2p-rendering-computation

Makefile
=> fixed command issue in MakeFile

cmd/action.go, cmd/flags.go
```
--AddServer value   Adds server IP address to iptables [$ADD_SERVER]
```
Completes issue: #17
=> added cli command add server

server/docker/containers/cpuhorovod/Dockerfile
Possibility to use ifconfig in docker containers
=> added net tools

p2p/ip_table.json, p2p/speedtest.go
=> fixed list slice error

cmd/action.go, cmd/flags.go, config/config.go, p2p/ip_table.json, p2p/iptable.go, p2p/iptable_test.go
```
--NetworkInterfaces
```
```
(0) lo : 127.0.0.1/8 
(1) lo : ::1/128 
(0) wlp0s20f3 : <ipv4 address>
(1) wlp0s20f3 : <ipv6 address>
(2) wlp0s20f3 : <ipv6 address>
(3) wlp0s20f3 : fe80::9cfa:ba73:66eb:8de8/64 
(0) docker0 : 172.17.0.1/16 
```
=> adds ipv6 index to config and a cli command to view network interface

Docs/Installation.md, p2p/ip_table.json
Updated installation  with paths to be added to ```.bashrc``` and with a note suggesting to add IPV6 to the config file.
=> updated installation docs

Docs/Installation.md, index.html
=> added index.html page

.gitignore, cmd/action.go, cmd/flags.go, config/config.go, deploy/roles/rsync/tasks/main.yml, main.go, plugin/plugin.go, plugin/plugin_test.go, sample-run/tensorflow/roles/rsync/tasks/main.yml, server/docker/docker.go
Implemented similar to the flag ```--vi```. 
```
// Plugins Array of all plugins detected
type Plugins struct {
PluginsDetected []*Plugin
}
// Plugin Information about the plugins available
type Plugin struct {
FolderName         string
PluginDescription  string
}
```
```--vp```
```
{
"PluginsDetected": [
{
"FolderName": "TestAnsible",
"PluginDescription": "Test if it's detected"
}
]
}
```
Partial implementation of the issue #47
=> Detection of plugins 

.gitignore, Docs/Implementation.md, Docs/Installation.md, Docs/PluginImplementation.md, Docs/README.md, Makefile, deploy/TestAnsible/description.txt, deploy/TestAnsible/hosts, deploy/TestAnsible/site.yml, go.mod, go.sum, plugin/TestAnsible/description.txt, plugin/TestAnsible/hosts, plugin/TestAnsible/site.yml, plugin/generate_test_case.sh, plugin/plugin.go, plugin/plugin_test.go
The plugin module is designed to ensure clients can execute instructions in a declarative manner across different 
containers created. This means the user (i.e client) needs to write the instruction only once, and these instructions 
can be executed across different nodes in a repetitive manner. 
In the scenario of this project Ansibles will be used as the way the users can create these instructions. 
The plugin module introduces a new path to the config file known as pluginpath. This path by defaults points to
```${P2PRC}/plugin/deploy```. Any file/folder inside ```plugin/deploy``` is part of the .gitginore. Plugins are 
detected by folder names inside the ```plugin/deploy```. 
```
plugin
|___ Deploy 
|___<plugin name>
|___ site.yml 
|___ hosts
|___ description.txt 
.
. 
.
n: n number of …
```
=> Plugin module implementation 

index.html
We always have deployment of p2prc on a cloud server as test net. This is so that clients and servers can learn about other client servers available. 
One which is for the master branch and another one for v1.0.0.
=> Updated website with new ip address 

Docs/Installation.md, client/TrackContainers.go, client/trackcontainers/trackcontainers.json, cmd/action.go, cmd/flags.go, plugin/plugin.go, plugin/plugin_test.go, server/docker/containers/docker-ubuntu-sshd-x11/Dockerfile, server/docker/containers/docker-ubuntu-sshd-x11/README.md, server/docker/containers/docker-ubuntu-sshd-x11/description.txt, server/docker/containers/docker-ubuntu-sshd-x11/ports.json, server/docker/containers/docker-ubuntu-sshd-x11/scripts/start, server/docker/containers/docker-ubuntu-sshd/ports.json
```
p2prc --plugin TestAnsible --id 858912730fb34f3cce38ef6d405e04519e44f50c2a496cd400e75aaa0def3c80
```
```
success ── 
success ── PLAY [all] ******************************************************************************************************************************
success ── 
success ── TASK [Gathering Facts] ******************************************************************************************************************
success ── ok: [host1]
success ── 
success ── TASK [simple-ansibleplaybook] ***********************************************************************************************************
success ── ok: [host1] => {
success ──     "msg": "Your are running 'simple-ansibleplaybook' example"
success ── }
success ── 
success ── PLAY RECAP …
```
=> Added possibility to execute plugin from Cli 

CITATION.cff
Allows easy citation of the repository via the GitHub website
=> Creates CITATION.cff file

index.html
This PR includes multiple commits that change `index.html` slowly to meet basic HTML5 standards.
Thereby making the viewing website more accessible too
As well as some minor edits here and there too 😌
=> Changes to `index.html`

README.md
Using Discord's API, the server invite is now a bit more colourful, displayed with Discord's colours.
Along with a hyperlink within the Banner to allow the user to join the server
=> Adds a Discord Banner for more vivid display

config/config.go, config/config_test.go, index.html
Add custom variable to extend the use case of P2PRC . The code snippet below shows a sample 
implementation of the following PR. 
```go
// sample implementation 
import (
"git.sr.ht/~akilan1999/p2p-rendering-computation/config"
)
// Main function 
func main(){
// Sets the Env variable name to TEST
config.SetEnvName("TEST")
// Reads from the config file based on the path 
// provided in the env variable TEST
config.ConfigInit()
}
```
=> added the possiblility to add custom varaibles

index.html, style.css
Follows Material Design standards for Dark Theme principles
1. Changes the Background and Text Color to match reading the park in Dark Mode.
2. Creates a new `style.css` file to add more features easily
3. Adds a color palette for the `<a>` tags (mainly for the `:link`, `:visited`, and `:hover` selectors)
There is only 1 issue left although:
Reference: [Material Design - Dark Theme](https://material.io/design/color/dark-theme.html)
=> P2PRC Website - Adds Dark Mode Support

client/clientIPTable/Iptable.go, p2p/iptable.go
[added mutex to avoid race condition when writing to iptable file](https://github.com/Akilan1999/p2p-rendering-computation/commit/256998d96475fef0814168e077f5fa66ed0354bc)
=> Added mutex to avoid race condition when writing to iptable file

CITATION.cff
Updates the version number and the release date as per the new [v2.0.0 release](https://github.com/Akilan1999/p2p-rendering-computation/releases/tag/v2.0.0) on June 8th.
=> Updates the `CITATION.cff` file

default.nix
I have added nix shell development environemnt. You just need to run "nix-shell" to activate it.
This initial configuration install:
- go language
- tmux
=> adding nix shell development environment

default.nix
modifying nix files, adding adding building, and docker (VIM as well)
=> modifying nix config

.gitignore, Makefile, flake.lock, flake.nix, gomod2nix.toml, shell.nix
Hi there,
I added a new changes to allow nix flake development environment. It creates a new toml file that keeps track of the packages being used for greater reproducibility.
I plan on adding the build environment for the go program, on a future commit.
Let me know if you need more information about this pull request.
=> Nix Flake development environment

Bindings/Client.go, Bindings/python/library.py, Bindings/python/test.py, abstractions/base.go
Added go binding and python function call to add custom information.
=> Python addcustom information
